rpl: Remove unused variable when building with ENABLE_DEBUG=1
Fixes
    /data/riotbuild/riotbase/sys/net/gnrc/routing/rpl/gnrc_rpl.c:28:13: error: 'addr_str' defined but not used [-Werror=unused-variable]
     static char addr_str[IPV6_ADDR_MAX_STR_LEN];
                  ^
when building with #define ENABLE_DEBUG (1)